host: localhost:8086
info:
  contact:
    name: Nurzhanat Zhussup
    url: https://github.com/nzhussup
  description: This is the API for generating summary from user profile data.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Summarizer Service API
  version: 1.0.0
paths:
  /v1/summarizer:
    get:
      description: Fetches personal data, generates a summary using LLM, and returns
        the professional bio summary.
      produces:
      - application/json
      responses:
        "200":
          description: Professional summary string
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get summarized profile
      tags:
      - summarizer
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
