host: localhost:8086
info:
  contact:
    name: Nurzhanat Zhussup
    url: https://github.com/nzhussup
  description: This is the API for generating summary from user profile data.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Summarizer Service API
  version: 1.0.0
paths:
  /v1/health:
    get:
      description: Checks the connectivity and health of dependent services, particularly
        Redis.
      produces:
      - application/json
      responses:
        "200":
          description: Status OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Redis connection failed
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check endpoint
      tags:
      - health
  /v1/summarizer:
    get:
      description: Retrieves structured personal data (e.g., work experience, education),
        generates a professional summary using a large language model (LLM), and returns
        it in the requested language.
      parameters:
      - description: 'Language code for the summary output. Supported values: ''en''
          (English), ''kz'' (Kazakh), ''de'' (German). Defaults to ''en''.'
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Generated professional summary
          schema:
            type: string
        "500":
          description: Internal server error with error details
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Generate professional profile summary
      tags:
      - summarizer
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
