name: API Gateway CI/CD

on:
  push:
    paths:
      - "backend/api-gateway/**"

jobs:
  call-service-cicd:
    uses: ./.github/workflows/common/backend-cicd.yml
    with:
      service_name: api-gateway
      service_path: backend/api-gateway
