name: API Gateway CI/CD

on:
  push:
    paths:
      - "backend/api-gateway/**"

jobs:
  call-service-cicd:
    uses: ../backend-cicd-template.yml
    with:
      service_name: api-gateway
      service_path: backend/api-gateway
      lang: java
