name: Feature Branch Backend CI/CD for Test and Build

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string
      lang:
        required: true
        type: string
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: ${{ inputs.lang == 'go' || inputs.lang == 'java' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Go Tests
        if: ${{ inputs.lang == 'go' }}
        run: |
          go test ./... -v
        working-directory: ${{ inputs.service_path }}

      - name: Set up Java
        if: ${{ inputs.lang == 'java' }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run Java Tests
        if: ${{ inputs.lang == 'java' }}
        run: |
          ./mvnw test
        working-directory: ${{ inputs.service_path }}
