name: Base Service CI/CD

on:
  push:
    paths:
      - "backend/base-service/**"
  workflow_dispatch:
jobs:
  call-service-cicd:
    uses: ./.github/workflows/backend-cicd-template.yml
    with:
      service_name: base-service
      service_path: backend/base-service
      lang: java
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
