name: Discovery Server CI/CD

on:
  push:
    paths:
      - "backend/discovery-server/**"

jobs:
  call-service-cicd:
    uses: ./.github/workflows/backend-cicd-template.yml
    with:
      service_name: discovery-server
      service_path: backend/discovery-server
      lang: java
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
