name: Create GitHub Release
on:
  push:
    tags:
      - "v*.*.*" # trigger on semantic version tags like v2.3.0
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract changelog entry for tag
        id: changelog
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG_STRIPPED="${TAG#v}"
          echo "Extracting changelog for tag: $TAG_STRIPPED"

          # Escape dots for regex
          TAG_ESCAPED=$(echo "$TAG_STRIPPED" | sed 's/\./\\./g')

          # Use awk to extract section between matching [TAG] and the next version heading
          ENTRY=$(awk -v tag="\\[$TAG_ESCAPED\\]" '
            $0 ~ tag { in_section = 1; next }
            in_section && $0 ~ /^\s*#+ \[[0-9]+\.[0-9]+\.[0-9]+.*\]/ { exit }
            in_section { print }
          ' CHANGELOG.md)

          if [ -z "$ENTRY" ]; then
            echo "❌ No changelog entry found for $TAG_STRIPPED"
            grep -E '^#+ \[[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md || true
            exit 1
          fi

          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          echo "$ENTRY" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
