name: Create GitHub Release

on:
  push:
    tags:
      - "v*.*.*" # trigger on semantic version tags like v2.3.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract changelog entry for tag
        id: changelog
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Looking for changelog for $TAG"

          changelog=$(awk "/^### \\[$TAG\\]/ {flag=1; next} /^### \\[/ {flag=0} flag" CHANGELOG.md | sed '/^\s*$/d')

          if [ -z "$changelog" ]; then
            echo "❌ No changelog entry found for $TAG"
            exit 1
          fi

          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          echo "$changelog" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
