name: Create GitHub Release

on:
  push:
    tags:
      - "v*.*.*" # trigger on semantic version tags like v2.3.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract changelog entry for tag
        id: changelog
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Extracting changelog for tag: $TAG"

          # Escape dots for regex match
          TAG_ESCAPED=$(echo "$TAG" | sed 's/\./\\./g')

          # Use sed to extract everything between the header of this tag and the next header
          ENTRY=$(sed -n "/^### \[$TAG_ESCAPED\]/,/^### \[/p" CHANGELOG.md | sed '1d;$d')

          if [ -z "$ENTRY" ]; then
            echo "❌ No changelog entry found for $TAG"
            exit 1
          fi

          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          echo "$ENTRY" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
